# Table of Contents
[[#Errors]]
- [[#Catching Errors]]
- [[#Else, Ensure, and Retry]]
- [[#Error Methods]]
- [[#Raising Errors]]
- [[#Creating Custom Errors]]

---
## Errors
All Errors are a subclass of Exception. A list of common errors is below.
- `StandardError`: Default error that can be caught. All other errors listed are an instance of StandardError
- `IOError`
	- `EOFError`
- `NameError`: When the given name of a variable is invalid
	- `NoMethodError`
- `RegexpError`: Invalid Regex expression
- `RuntimeError`: Default error to be thrown
- `TypeError`
- `ZeroDivisionError`

For large projects, it's generally a good idea to put all [[#Creating Custom Errors|custom error declarations]] in a separate file / library

>Ruby has an Exception class, but it is better to not mess with it as it encompasses all Errors including the ones out of the programmers control, like NoMemoryError and SystemStackError (stack overflow). Akin to the Error class in Java

### Catching Errors
- To catch errors (equivalent to exceptions in Java) in Ruby, use `rescue` blocks
- Surround code in question with `begin` and use `rescue` to catch the error
	- being = try
	- rescue = catch
- Not specifying a type of error to catch with the rescue block leads to it catching all errors

```rb
# catch all errors
begin 
	arr = [0, 4, 5]
	x = 10 / 0
	arr["number"]
rescue
	puts "General Error"
end

begin 
	arr = [0, 4, 5]
	y = gets.chomp
	arr[y] = 10 / y
rescue ZeroDivisionError
	puts "Divide by 0 error"
rescue TypeError
	puts "Type Error"
end
```

Can also assign the error to a variable and print the error
- Printing the error will print it's cause/message
- Can do this with a rocket `=>`
- Do not need to define the variable beforehand

```rb
begin
	arr = [0, 4, 5]
	arr["cat"]
rescue TypeError => e
	puts e # will put "no implicit conversion of String into Integer"
end
```

### Else, Ensure, and Retry
- `else` in this context goes after a `rescue` block and will execute if no errors were raised
- `ensure` acts as a `finally` block, always executing after the `begin` block, or `rescue`/`else` blocks

- The `retry` keyword can be used in a rescue statement to retry the entire begin..end clause.
	- Generally used in rescue statements although can be used in other places
```rb
def divide
	begin 
		x = gets.chomp
		puts 10 / x
	rescue 
		puts "Please enter a non-zero number"
		retry #acts as a goto statement to the line with begin
	else
		puts "Congrats for not typing 0!"
	ensure
		puts "not necessary here but I always run"
	end
end
```

### Error Methods
The following methods can be executed on an error object. These can (and probably should) be used when rescuing errors
- `backtrace` - returns an array containing a backtrace leading up to the error. Can be useful to print the whole thing or get the most recent entries.
	- To print efficiently, use `puts e.backtrace.join("\n")` where `e` is the name of the variable the error is stored in
- `inspect` - returns the exceptions class name and message
- `message` - technically returns the same as invoking `exception.to_s` but generally is the message of the exception or its name if no message is set
- `class` - get the class of the error (this exists for all objects, but should be highlighted here)

### Raising Errors
Can throw your own errors using the `raise` keyword
- By itself, `raise` will raise a `RuntimeError` with no message
- Can specify a message by putting it after the `raise` statement
	- `raise "my message"`
- Can specify a custom error to raise (that is not RuntimeError) using the same syntax as above
	- `raise TypeError`
- To specify a custom error and a message, use a comma with the error type coming first
	- `raise TypeError, "my message"`

```rb
raise # RuntimeError - no message
raise "dont" #RuntimeError - message: "dont"
raise NameError #NameError - no message
raise TypeError, "Need Int" #TypeError - message: "Need Int"
```

### Creating Custom Errors
Can create custom errors via making a class that inherits from `StandardError` (or `RuntimeError`). Inheriting from one of these means it can be its own general error and still be caught by general `rescue` statements.

All that is needed is for the class to exist and inherit the Standard or Runtime Error class
```rb
# Bare minimum
class MyError < StandardError
end
```
- With this, a custom `MyError` error can be raised and given a message using the syntax `raise MyError, "custom message"`

Can provide the exception a custom default message using the following
```rb
# Custom default message
class MyError < StandardError
	def initialize(msg="Default Error Message")
		super
	end
end
```
- With this, a custom `MyError` error can be raised, and without specifying a message the default message will be used
	- so `raise MyError` will raise a `MyError` with the message "Default Error Message"

Can also add extra data to the exception if needed and add a reader to access it. To use the extra data while raising the exception, it needs to be created using `new`
```rb
class MyError < StandardError
	attr_reader :thing
	# Default value for thing is apple
	def initialize(msg="My default message", thing="apple")
		@thing = thing
		super(msg)
	end
end

begin
	#To use the new data attribute raise the exception with new
	raise MyError.new("my message", "my thing") 
rescue => e
	puts e.thing # "my thing"
end
```
